[2025-07-06 17:19:40,982] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:19:46,167] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:19:46,168] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:19:46,183] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:19:46,183] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:19:46,202] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:19:46,202] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:19:46,208] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 17:19:46,346] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:19:46,346] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:19:46,369] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 17:19:47,415] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:19:47,415] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:20:07,881] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:20:08,152] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:20:12,202] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:20:12,476] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:20:15,296] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:20:15,296] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:20:15,315] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:20:15,315] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:20:15,334] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:20:15,334] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:20:15,339] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 17:20:15,414] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:20:15,414] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:20:15,424] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 17:20:15,457] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:20:15,459] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
