[2025-07-06 17:14:29,842] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:14:35,127] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\app.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:14:35,390] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:14:45,441] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:14:45,442] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:14:45,457] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:14:45,457] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:14:45,476] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:14:45,476] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:14:45,484] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 17:14:45,504] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:14:45,505] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:14:45,517] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 17:14:45,554] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:14:45,554] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:30,866] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:18:31,138] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:18:36,629] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:36,629] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:36,646] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:36,646] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:36,663] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:36,664] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:36,670] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 17:18:36,746] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:36,746] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:36,756] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 17:18:44,588] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:18:44,880] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:18:48,600] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:48,600] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:48,616] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:48,617] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:48,635] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:48,636] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:48,641] WARNING get_pessoa() L203  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L203 
[2025-07-06 17:18:48,714] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:48,714] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:18:48,724] WARNING delete_paciente() L242  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L242 
[2025-07-06 17:18:48,763] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:18:48,765] ERROR predict() L152  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L152 
[2025-07-06 17:19:26,801] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:19:27,065] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:19:33,288] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:19:33,531] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:19:40,731] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
