[2025-07-06 16:50:42,346] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:51:18,465] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:51:18,481] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:51:18,500] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:51:18,507] WARNING get_pessoa() L200  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L200 
[2025-07-06 16:51:18,578] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:51:18,587] WARNING delete_paciente() L239  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L239 
[2025-07-06 16:51:18,624] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:52:35,914] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:52:36,168] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:52:39,510] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:52:39,527] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:52:39,546] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:52:39,554] WARNING get_pessoa() L200  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L200 
[2025-07-06 16:52:39,630] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:52:39,641] WARNING delete_paciente() L239  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L239 
[2025-07-06 16:52:44,545] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:52:44,811] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:53:15,363] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:53:15,591] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:53:21,773] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_api.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:53:22,050] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:53:26,098] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:53:26,115] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:53:26,134] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:53:26,140] WARNING get_pessoa() L200  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L200 
[2025-07-06 16:53:26,211] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:53:26,221] WARNING delete_paciente() L239  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L239 
[2025-07-06 16:53:26,263] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 16:58:12,886] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_modelos.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:58:13,152] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:58:18,462] INFO _log() L97    * Detected change in 'C:\\Users\\Fadami\\Downloads\\Lucas Samel\\Puc\\AutoInsight\\api\\test_modelos.py', reloading - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 16:58:18,727] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:09:25,513] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:09:25,514] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:09:25,515] INFO _log() L97    * Restarting with stat - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:09:31,284] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:09:31,301] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:09:31,324] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:09:31,331] WARNING get_pessoa() L200  Erro ao buscar produto 'PessoaInexistente', Pessoa PessoaInexistente não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L200 
[2025-07-06 17:09:31,349] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:09:31,364] WARNING delete_paciente() L239  Erro ao deletar pessoa 'PessoaInexistente', Pessoa não encontrado na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L239 
[2025-07-06 17:09:31,416] WARNING predict() L149  Erro ao adicionar pessoa 'Maria', Essa Pessoa já existente na base :/ - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\api\app.py L149 
[2025-07-06 17:11:05,124] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 17:11:05] "POST /pessoa HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 17:11:18,448] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 17:11:18] "POST /pessoa HTTP/1.1" 200 - - call_trace=C:\Users\Fadami\Downloads\Lucas Samel\Puc\AutoInsight\venv\Lib\site-packages\werkzeug\_internal.py L97  
